### ISSUE TITLE
Add ability to store entity/block models as files in the assets folder

### ISSUE THREAD

**Issue by OneAvargeCoder193** [PixelGuys/Cubyz#510] opened 2024-06-21 01:13 UTC
This could be very helpful for modding as right now all the models are hard coded. There could be a models/entities and models/blocks folder for the different uses of models. Additionaly, for block models, each part of the model should be able to be turned on and off based on the rotation mode. (But that is a little far into the future)

**Comment by IntegratedQuantum** [comment] 2024-06-21 10:47
Duplicate of #290

**Closed by IntegratedQuantum** 2024-06-21 10:47 UTC
