### ISSUE TITLE
[Feature Request] Create new world button

### ISSUE THREAD

**Issue by b-risk** [PixelGuys/Cubyz#316] opened 2024-04-13 21:22 UTC
Probably my issue for not knowing how anything worked and clicking on random buttons lol but I clicked on delete right next to "development" and now the window shows up completely minimized not letting me click on it or anything,
my guess is I deleted my only world and creating a new one via a file or something would fix it but I'm not sure how to go about it. I'll probably just reinstall the game in the meantime.
![image](https://github.com/PixelGuys/Cubyz/assets/89107446/bdd5779a-1c57-4e9f-8d05-0ba410c539c7)

**Comment by IntegratedQuantum** [comment] 2024-04-13 21:47
Duplicate of #79.
Sorry the rewrite just isn't quite there yet. You'll need to redownload the game.

**Closed by IntegratedQuantum** 2024-04-13 21:47 UTC
