### ISSUE TITLE
Blocks around the player are culled. Entity models might contribute to culling.

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#792] opened 2024-11-23 18:06 UTC
https://github.com/user-attachments/assets/eb3585d2-ce31-42d3-9992-1fe511b014d7

**Comment by IntegratedQuantum** [comment] 2024-11-23 20:20
This is a duplicate of #765.

This issue seems to be more widespread and problematic than I thought, I guess I have to revert the fix for #696.

**Closed by IntegratedQuantum** 2024-11-23 20:20 UTC
Labels: bug, optimization, graphics, engine
