### ISSUE TITLE
Every Biome displays as "cubyz:jungle(TODO)"

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#796] opened 2024-11-25 03:41 UTC
![image](https://github.com/user-attachments/assets/33a45727-4de2-48cc-b3bc-ca9fd7df37be)

**Comment by IntegratedQuantum** [comment] 2024-11-25 15:12
duplicate of #794, biome and time are sent in the same network packet.

**Closed by IntegratedQuantum** 2024-11-25 15:12 UTC
Labels: bug
