### ISSUE TITLE
jumping then immediately pressing forward will not allow you to scale 1 block jumps

### ISSUE THREAD

**Issue by LinaPlusPlus** [PixelGuys/Cubyz#578] opened 2024-07-17 10:12 UTC
it is currently impossible to jump over a single block unless you initially held forward because there is no air strafing.

**Comment by archbirdplus** [comment] 2024-07-17 10:14
Just like real life :(
I think this was a deliberate feature. In any case, this is a duplicate of #506.

**Comment by LinaPlusPlus** [comment] 2024-07-17 11:07
I actually like the feature, there should be an exception specifically for 1 block jumps

**Comment by IntegratedQuantum** [comment] 2024-07-17 11:20
Well actually it's not related to #506. You need very little air control to jump onto a block when you start right next to it.
The problem is just that currently the spring system pushes you so far from the block when standing still, that you are always too far away.

**Closed** 2024-07-19 13:41 UTC
Labels: bug, physics
