### ISSUE TITLE
Long-term: Allow blocks to change player physics

### ISSUE THREAD

**Issue by ikabod-kee** [PixelGuys/Cubyz#582] opened 2024-07-19 10:48 UTC
Examples:
Water makes the player's gravity and terminal velocity lower, as well as their speed
Leaves lower the player's gravity and speed, but not their terminal velocity
Ice has reduced friction
Etc.

**Comment by IntegratedQuantum** [comment] 2024-07-19 11:57
I would say this is a duplicate of #83

**Closed by IntegratedQuantum** 2024-07-19 11:57 UTC
