### ISSUE TITLE
[Bug] LODs are sometimes inaccurate

### ISSUE THREAD

**Issue by Moonyol** [PixelGuys/Cubyz#596] opened 2024-07-28 11:13 UTC
from far away there is a tree
![image](https://github.com/user-attachments/assets/ec9c64a3-92eb-4857-a7a9-0a40bf23012e)
from close up there isn't
![image](https://github.com/user-attachments/assets/672f0a30-ec2b-4f0b-9b95-096d14113dbb)

Seed: 4232237, Position: -232 -1673 89

**Comment by IntegratedQuantum** [comment] 2024-07-28 12:42
Duplicate of #184

**Closed by IntegratedQuantum** 2024-07-28 12:42 UTC
