### ISSUE TITLE
Everything is grayscale (and I love it!)

### ISSUE THREAD

**Issue by du82** [PixelGuys/Cubyz#234] opened 2023-12-11 02:27 UTC
I dont know if this is an actual issue or intentional, but I love it. The atmosphere is amazing, the music is amazing, I've spent hours playing the game, flying around the terrain and wondering what might be out there.

Also, where's the music from? I think I've heard it before. The whole game is just very eerily inviting and it warms my heart.

![Screenshot from 2023-12-10 20-19-27](https://github.com/PixelGuys/Cubyz/assets/65834069/3253f06a-ff39-4ec1-a33c-2948ca8aced3)

**Comment by IntegratedQuantum** [comment] 2023-12-11 08:17
This is a duplicate of #218, there is no sunlight propagation yet so the world is dark.
The music is from kevin macleod. Many people use his free music, including many films.

**Closed by IntegratedQuantum** 2023-12-11 08:17 UTC
